<div class="columns">
<div class="col1 clearfix">
<h4>40 New Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-angellist fa-1x"></i> fa-angellist</li>
<li><i class="fa fa-area-chart fa-1x"></i> fa-area-chart</li>
<li><i class="fa fa-at fa-1x"></i> fa-at</li>
<li><i class="fa fa-bell-slash fa-1x"></i> fa-bell-slash</li>
<li><i class="fa fa-bell-slash-o fa-1x"></i> fa-bell-slash-o</li>
<li><i class="fa fa-bicycle fa-1x"></i> fa-bicycle</li>
<li><i class="fa fa-binoculars fa-1x"></i> fa-binoculars</li>
<li><i class="fa fa-birthday-cake fa-1x"></i> fa-birthday-cake</li>
<li><i class="fa fa-bus fa-1x"></i> fa-bus</li>
<li><i class="fa fa-calculator fa-1x"></i> fa-calculator</li>
<li><i class="fa fa-cc fa-1x"></i> fa-cc</li>
<li><i class="fa fa-cc-amex fa-1x"></i> fa-cc-amex</li>
<li><i class="fa fa-cc-discover fa-1x"></i> fa-cc-discover</li>
<li><i class="fa fa-cc-mastercard fa-1x"></i> fa-cc-mastercard</li>
<li><i class="fa fa-cc-paypal fa-1x"></i> fa-cc-paypal</li>
<li><i class="fa fa-cc-stripe fa-1x"></i> fa-cc-stripe</li>
<li><i class="fa fa-cc-visa fa-1x"></i> fa-cc-visa</li>
<li><i class="fa fa-copyright fa-1x"></i> fa-copyright</li>
<li><i class="fa fa-eyedropper fa-1x"></i> fa-eyedropper</li>
<li><i class="fa fa-futbol-o fa-1x"></i> fa-futbol-o</li>
<li><i class="fa fa-google-wallet fa-1x"></i> fa-google-wallet</li>
<li><i class="fa fa-ils fa-1x"></i> fa-ils</li>
<li><i class="fa fa-ioxhost fa-1x"></i> fa-ioxhost</li>
<li><i class="fa fa-lastfm fa-1x"></i> fa-lastfm</li>
<li><i class="fa fa-lastfm-square fa-1x"></i> fa-lastfm-square</li>
<li><i class="fa fa-line-chart fa-1x"></i> fa-line-chart</li>
<li><i class="fa fa-meanpath fa-1x"></i> fa-meanpath</li>
<li><i class="fa fa-newspaper-o fa-1x"></i> fa-newspaper-o</li>
<li><i class="fa fa-paint-brush fa-1x"></i> fa-paint-brush</li>
<li><i class="fa fa-paypal fa-1x"></i> fa-paypal</li>
<li><i class="fa fa-pie-chart fa-1x"></i> fa-pie-chart</li>
<li><i class="fa fa-plug fa-1x"></i> fa-plug</li>
<li><i class="fa fa-shekel fa-1x"></i> fa-shekel <small>(alias)</small></li>
<li><i class="fa fa-sheqel fa-1x"></i> fa-sheqel <small>(alias)</small></li>
<li><i class="fa fa-slideshare fa-1x"></i> fa-slideshare</li>
<li><i class="fa fa-soccer-ball-o fa-1x"></i> fa-soccer-ball-o <small>(alias)</small></li>
<li><i class="fa fa-toggle-off fa-1x"></i> fa-toggle-off</li>
<li><i class="fa fa-toggle-on fa-1x"></i> fa-toggle-on</li>
<li><i class="fa fa-trash fa-1x"></i> fa-trash</li>
<li><i class="fa fa-tty fa-1x"></i> fa-tty</li>
<li><i class="fa fa-twitch fa-1x"></i> fa-twitch</li>
<li><i class="fa fa-wifi fa-1x"></i> fa-wifi</li>
<li><i class="fa fa-yelp fa-1x"></i> fa-yelp</li>
</ul>

<h4>Web Application Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-adjust fa-1x"></i> fa-adjust</li>
<li><i class="fa fa-anchor fa-1x"></i> fa-anchor</li>
<li><i class="fa fa-archive fa-1x"></i> fa-archive</li>
<li><i class="fa fa-area-chart fa-1x"></i> fa-area-chart</li>
<li><i class="fa fa-arrows fa-1x"></i> fa-arrows</li>
<li><i class="fa fa-arrows-h fa-1x"></i> fa-arrows-h</li>
<li><i class="fa fa-arrows-v fa-1x"></i> fa-arrows-v</li>
<li><i class="fa fa-asterisk fa-1x"></i> fa-asterisk</li>
<li><i class="fa fa-at fa-1x"></i> fa-at</li>
<li><i class="fa fa-automobile fa-1x"></i> fa-automobile <small>(alias)</small></li>
<li><i class="fa fa-ban fa-1x"></i> fa-ban <small>(alias)</small></li>
<li><i class="fa fa-bank fa-1x"></i> fa-bank <small>(alias)</small></li>
<li><i class="fa fa-bar-chart fa-1x"></i> fa-bar-chart</li>
<li><i class="fa fa-bar-chart-o fa-1x"></i> fa-bar-chart-o <small>(alias)</small></li>
<li><i class="fa fa-barcode fa-1x"></i> fa-barcode</li>
<li><i class="fa fa-bars fa-1x"></i> fa-bars</li>
<li><i class="fa fa-beer fa-1x"></i> fa-beer</li>
<li><i class="fa fa-bell fa-1x"></i> fa-bell</li>
<li><i class="fa fa-bell-o fa-1x"></i> fa-bell-o</li>
<li><i class="fa fa-bell-slash fa-1x"></i> fa-bell-slash</li>
<li><i class="fa fa-bell-slash-o fa-1x"></i> fa-bell-slash-o</li>
<li><i class="fa fa-bicycle fa-1x"></i> fa-bicycle</li>
<li><i class="fa fa-binoculars fa-1x"></i> fa-binoculars</li>
<li><i class="fa fa-birthday-cake fa-1x"></i> fa-birthday-cake</li>
<li><i class="fa fa-bolt fa-1x"></i> fa-bolt</li>
<li><i class="fa fa-bomb fa-1x"></i> fa-bomb</li>
<li><i class="fa fa-book fa-1x"></i> fa-book</li>
<li><i class="fa fa-bookmark fa-1x"></i> fa-bookmark</li>
<li><i class="fa fa-bookmark-o fa-1x"></i> fa-bookmark-o</li>
<li><i class="fa fa-briefcase fa-1x"></i> fa-briefcase</li>
<li><i class="fa fa-bug fa-1x"></i> fa-bug</li>
<li><i class="fa fa-building fa-1x"></i> fa-building</li>
<li><i class="fa fa-building-o fa-1x"></i> fa-building-o</li>
<li><i class="fa fa-bullhorn fa-1x"></i> fa-bullhorn</li>
<li><i class="fa fa-bullseye fa-1x"></i> fa-bullseye</li>
<li><i class="fa fa-bus fa-1x"></i> fa-bus</li>
<li><i class="fa fa-cab fa-1x"></i> fa-cab <small>(alias)</small></li>
<li><i class="fa fa-calculator fa-1x"></i> fa-calculator</li>
<li><i class="fa fa-calendar fa-1x"></i> fa-calendar</li>
<li><i class="fa fa-calendar-o fa-1x"></i> fa-calendar-o</li>
<li><i class="fa fa-camera fa-1x"></i> fa-camera</li>
<li><i class="fa fa-camera-retro fa-1x"></i> fa-camera-retro</li>
<li><i class="fa fa-car fa-1x"></i> fa-car</li>
<li><i class="fa fa-caret-square-o-down fa-1x"></i> fa-caret-square-o-down</li>
<li><i class="fa fa-caret-square-o-left fa-1x"></i> fa-caret-square-o-left</li>
<li><i class="fa fa-caret-square-o-right fa-1x"></i> fa-caret-square-o-right</li>
<li><i class="fa fa-caret-square-o-up fa-1x"></i> fa-caret-square-o-up</li>
<li><i class="fa fa-cc fa-1x"></i> fa-cc</li>
<li><i class="fa fa-certificate fa-1x"></i> fa-certificate</li>
<li><i class="fa fa-check fa-1x"></i> fa-check</li>
<li><i class="fa fa-check-circle fa-1x"></i> fa-check-circle</li>
<li><i class="fa fa-check-circle-o fa-1x"></i> fa-check-circle-o</li>
<li><i class="fa fa-check-square fa-1x"></i> fa-check-square</li>
<li><i class="fa fa-check-square-o fa-1x"></i> fa-check-square-o</li>
<li><i class="fa fa-child fa-1x"></i> fa-child</li>
<li><i class="fa fa-circle fa-1x"></i> fa-circle</li>
<li><i class="fa fa-circle-o fa-1x"></i> fa-circle-o</li>
<li><i class="fa fa-circle-o-notch fa-1x"></i> fa-circle-o-notch</li>
<li><i class="fa fa-circle-thin fa-1x"></i> fa-circle-thin</li>
<li><i class="fa fa-clock-o fa-1x"></i> fa-clock-o</li>
<li><i class="fa fa-close fa-1x"></i> fa-close <small>(alias)</small></li>
<li><i class="fa fa-cloud fa-1x"></i> fa-cloud</li>
<li><i class="fa fa-cloud-download fa-1x"></i> fa-cloud-download</li>
<li><i class="fa fa-cloud-upload fa-1x"></i> fa-cloud-upload</li>
<li><i class="fa fa-code fa-1x"></i> fa-code</li>
<li><i class="fa fa-code-fork fa-1x"></i> fa-code-fork</li>
<li><i class="fa fa-coffee fa-1x"></i> fa-coffee</li>
<li><i class="fa fa-cog fa-1x"></i> fa-cog</li>
<li><i class="fa fa-cogs fa-1x"></i> fa-cogs</li>
<li><i class="fa fa-comment fa-1x"></i> fa-comment</li>
<li><i class="fa fa-comment-o fa-1x"></i> fa-comment-o</li>
<li><i class="fa fa-comments fa-1x"></i> fa-comments</li>
<li><i class="fa fa-comments-o fa-1x"></i> fa-comments-o</li>
<li><i class="fa fa-compass fa-1x"></i> fa-compass</li>
<li><i class="fa fa-copyright fa-1x"></i> fa-copyright</li>
<li><i class="fa fa-credit-card fa-1x"></i> fa-credit-card</li>
<li><i class="fa fa-crop fa-1x"></i> fa-crop</li>
<li><i class="fa fa-crosshairs fa-1x"></i> fa-crosshairs</li>
<li><i class="fa fa-cube fa-1x"></i> fa-cube</li>
<li><i class="fa fa-cubes fa-1x"></i> fa-cubes</li>
<li><i class="fa fa-cutlery fa-1x"></i> fa-cutlery</li>
<li><i class="fa fa-dashboard fa-1x"></i> fa-dashboard <small>(alias)</small></li>
<li><i class="fa fa-database fa-1x"></i> fa-database</li>
<li><i class="fa fa-desktop fa-1x"></i> fa-desktop</li>
<li><i class="fa fa-dot-circle-o fa-1x"></i> fa-dot-circle-o</li>
<li><i class="fa fa-download fa-1x"></i> fa-download</li>
<li><i class="fa fa-edit fa-1x"></i> fa-edit <small>(alias)</small></li>
<li><i class="fa fa-ellipsis-h fa-1x"></i> fa-ellipsis-h</li>
<li><i class="fa fa-ellipsis-v fa-1x"></i> fa-ellipsis-v</li>
<li><i class="fa fa-envelope fa-1x"></i> fa-envelope</li>
<li><i class="fa fa-envelope-o fa-1x"></i> fa-envelope-o</li>
<li><i class="fa fa-envelope-square fa-1x"></i> fa-envelope-square</li>
<li><i class="fa fa-eraser fa-1x"></i> fa-eraser</li>
<li><i class="fa fa-exchange fa-1x"></i> fa-exchange</li>
<li><i class="fa fa-exclamation fa-1x"></i> fa-exclamation</li>
<li><i class="fa fa-exclamation-circle fa-1x"></i> fa-exclamation-circle</li>
<li><i class="fa fa-exclamation-triangle fa-1x"></i> fa-exclamation-triangle</li>
<li><i class="fa fa-external-link fa-1x"></i> fa-external-link</li>
<li><i class="fa fa-external-link-square fa-1x"></i> fa-external-link-square</li>
<li><i class="fa fa-eye fa-1x"></i> fa-eye</li>
<li><i class="fa fa-eye-slash fa-1x"></i> fa-eye-slash</li>
<li><i class="fa fa-eyedropper fa-1x"></i> fa-eyedropper</li>
<li><i class="fa fa-fax fa-1x"></i> fa-fax</li>
<li><i class="fa fa-female fa-1x"></i> fa-female</li>
<li><i class="fa fa-fighter-jet fa-1x"></i> fa-fighter-jet</li>
<li><i class="fa fa-file-archive-o fa-1x"></i> fa-file-archive-o</li>
<li><i class="fa fa-file-audio-o fa-1x"></i> fa-file-audio-o</li>
<li><i class="fa fa-file-code-o fa-1x"></i> fa-file-code-o</li>
<li><i class="fa fa-file-excel-o fa-1x"></i> fa-file-excel-o</li>
<li><i class="fa fa-file-image-o fa-1x"></i> fa-file-image-o</li>
<li><i class="fa fa-file-movie-o fa-1x"></i> fa-file-movie-o <small>(alias)</small></li>
<li><i class="fa fa-file-pdf-o fa-1x"></i> fa-file-pdf-o</li>
<li><i class="fa fa-file-photo-o fa-1x"></i> fa-file-photo-o <small>(alias)</small></li>
<li><i class="fa fa-file-picture-o fa-1x"></i> fa-file-picture-o <small>(alias)</small></li>
<li><i class="fa fa-file-powerpoint-o fa-1x"></i> fa-file-powerpoint-o</li>
<li><i class="fa fa-file-sound-o fa-1x"></i> fa-file-sound-o <small>(alias)</small></li>
<li><i class="fa fa-file-video-o fa-1x"></i> fa-file-video-o</li>
<li><i class="fa fa-file-word-o fa-1x"></i> fa-file-word-o</li>
<li><i class="fa fa-file-zip-o fa-1x"></i> fa-file-zip-o <small>(alias)</small></li>
<li><i class="fa fa-film fa-1x"></i> fa-film</li>
<li><i class="fa fa-filter fa-1x"></i> fa-filter</li>
<li><i class="fa fa-fire fa-1x"></i> fa-fire</li>
<li><i class="fa fa-fire-extinguisher fa-1x"></i> fa-fire-extinguisher</li>
<li><i class="fa fa-flag fa-1x"></i> fa-flag</li>
<li><i class="fa fa-flag-checkered fa-1x"></i> fa-flag-checkered</li>
<li><i class="fa fa-flag-o fa-1x"></i> fa-flag-o</li>
<li><i class="fa fa-flash fa-1x"></i> fa-flash <small>(alias)</small></li>
<li><i class="fa fa-flask fa-1x"></i> fa-flask</li>
<li><i class="fa fa-folder fa-1x"></i> fa-folder</li>
<li><i class="fa fa-folder-o fa-1x"></i> fa-folder-o</li>
<li><i class="fa fa-folder-open fa-1x"></i> fa-folder-open</li>
<li><i class="fa fa-folder-open-o fa-1x"></i> fa-folder-open-o</li>
<li><i class="fa fa-frown-o fa-1x"></i> fa-frown-o</li>
<li><i class="fa fa-futbol-o fa-1x"></i> fa-futbol-o</li>
<li><i class="fa fa-gamepad fa-1x"></i> fa-gamepad</li>
<li><i class="fa fa-gavel fa-1x"></i> fa-gavel</li>
<li><i class="fa fa-gear fa-1x"></i> fa-gear <small>(alias)</small></li>
<li><i class="fa fa-gears fa-1x"></i> fa-gears <small>(alias)</small></li>
<li><i class="fa fa-gift fa-1x"></i> fa-gift</li>
<li><i class="fa fa-glass fa-1x"></i> fa-glass</li>
<li><i class="fa fa-globe fa-1x"></i> fa-globe</li>
<li><i class="fa fa-graduation-cap fa-1x"></i> fa-graduation-cap</li>
<li><i class="fa fa-group fa-1x"></i> fa-group <small>(alias)</small></li>
<li><i class="fa fa-hdd-o fa-1x"></i> fa-hdd-o</li>
<li><i class="fa fa-headphones fa-1x"></i> fa-headphones</li>
<li><i class="fa fa-heart fa-1x"></i> fa-heart</li>
<li><i class="fa fa-heart-o fa-1x"></i> fa-heart-o</li>
<li><i class="fa fa-history fa-1x"></i> fa-history</li>
<li><i class="fa fa-home fa-1x"></i> fa-home</li>
<li><i class="fa fa-image fa-1x"></i> fa-image <small>(alias)</small></li>
<li><i class="fa fa-inbox fa-1x"></i> fa-inbox</li>
<li><i class="fa fa-info fa-1x"></i> fa-info</li>
<li><i class="fa fa-info-circle fa-1x"></i> fa-info-circle</li>
<li><i class="fa fa-institution fa-1x"></i> fa-institution <small>(alias)</small></li>
<li><i class="fa fa-key fa-1x"></i> fa-key</li>
<li><i class="fa fa-keyboard-o fa-1x"></i> fa-keyboard-o</li>
<li><i class="fa fa-language fa-1x"></i> fa-language</li>
<li><i class="fa fa-laptop fa-1x"></i> fa-laptop</li>
<li><i class="fa fa-leaf fa-1x"></i> fa-leaf</li>
<li><i class="fa fa-legal fa-1x"></i> fa-legal <small>(alias)</small></li>
<li><i class="fa fa-lemon-o fa-1x"></i> fa-lemon-o</li>
<li><i class="fa fa-level-down fa-1x"></i> fa-level-down</li>
<li><i class="fa fa-level-up fa-1x"></i> fa-level-up</li>
<li><i class="fa fa-life-bouy fa-1x"></i> fa-life-bouy <small>(alias)</small></li>
<li><i class="fa fa-life-buoy fa-1x"></i> fa-life-buoy <small>(alias)</small></li>
<li><i class="fa fa-life-ring fa-1x"></i> fa-life-ring</li>
<li><i class="fa fa-life-saver fa-1x"></i> fa-life-saver <small>(alias)</small></li>
<li><i class="fa fa-lightbulb-o fa-1x"></i> fa-lightbulb-o</li>
<li><i class="fa fa-line-chart fa-1x"></i> fa-line-chart</li>
<li><i class="fa fa-location-arrow fa-1x"></i> fa-location-arrow</li>
<li><i class="fa fa-lock fa-1x"></i> fa-lock</li>
<li><i class="fa fa-magic fa-1x"></i> fa-magic</li>
<li><i class="fa fa-magnet fa-1x"></i> fa-magnet</li>
<li><i class="fa fa-mail-forward fa-1x"></i> fa-mail-forward <small>(alias)</small></li>
<li><i class="fa fa-mail-reply fa-1x"></i> fa-mail-reply <small>(alias)</small></li>
<li><i class="fa fa-mail-reply-all fa-1x"></i> fa-mail-reply-all <small>(alias)</small></li>
<li><i class="fa fa-male fa-1x"></i> fa-male</li>
<li><i class="fa fa-map-marker fa-1x"></i> fa-map-marker</li>
<li><i class="fa fa-meh-o fa-1x"></i> fa-meh-o</li>
<li><i class="fa fa-microphone fa-1x"></i> fa-microphone</li>
<li><i class="fa fa-microphone-slash fa-1x"></i> fa-microphone-slash</li>
<li><i class="fa fa-minus fa-1x"></i> fa-minus</li>
<li><i class="fa fa-minus-circle fa-1x"></i> fa-minus-circle</li>
<li><i class="fa fa-minus-square fa-1x"></i> fa-minus-square</li>
<li><i class="fa fa-minus-square-o fa-1x"></i> fa-minus-square-o</li>
<li><i class="fa fa-mobile fa-1x"></i> fa-mobile</li>
<li><i class="fa fa-mobile-phone fa-1x"></i> fa-mobile-phone <small>(alias)</small></li>
<li><i class="fa fa-money fa-1x"></i> fa-money</li>
<li><i class="fa fa-moon-o fa-1x"></i> fa-moon-o</li>
<li><i class="fa fa-mortar-board fa-1x"></i> fa-mortar-board <small>(alias)</small></li>
<li><i class="fa fa-music fa-1x"></i> fa-music</li>
<li><i class="fa fa-navicon fa-1x"></i> fa-navicon <small>(alias)</small></li>
<li><i class="fa fa-newspaper-o fa-1x"></i> fa-newspaper-o</li>
<li><i class="fa fa-paint-brush fa-1x"></i> fa-paint-brush</li>
<li><i class="fa fa-paper-plane fa-1x"></i> fa-paper-plane</li>
<li><i class="fa fa-paper-plane-o fa-1x"></i> fa-paper-plane-o</li>
<li><i class="fa fa-paw fa-1x"></i> fa-paw</li>
<li><i class="fa fa-pencil fa-1x"></i> fa-pencil</li>
<li><i class="fa fa-pencil-square fa-1x"></i> fa-pencil-square</li>
<li><i class="fa fa-pencil-square-o fa-1x"></i> fa-pencil-square-o</li>
<li><i class="fa fa-phone fa-1x"></i> fa-phone</li>
<li><i class="fa fa-phone-square fa-1x"></i> fa-phone-square</li>
<li><i class="fa fa-photo fa-1x"></i> fa-photo <small>(alias)</small></li>
<li><i class="fa fa-picture-o fa-1x"></i> fa-picture-o</li>
<li><i class="fa fa-pie-chart fa-1x"></i> fa-pie-chart</li>
<li><i class="fa fa-plane fa-1x"></i> fa-plane</li>
<li><i class="fa fa-plug fa-1x"></i> fa-plug</li>
<li><i class="fa fa-plus fa-1x"></i> fa-plus</li>
<li><i class="fa fa-plus-circle fa-1x"></i> fa-plus-circle</li>
<li><i class="fa fa-plus-square fa-1x"></i> fa-plus-square</li>
<li><i class="fa fa-plus-square-o fa-1x"></i> fa-plus-square-o</li>
<li><i class="fa fa-power-off fa-1x"></i> fa-power-off</li>
<li><i class="fa fa-print fa-1x"></i> fa-print</li>
<li><i class="fa fa-puzzle-piece fa-1x"></i> fa-puzzle-piece</li>
<li><i class="fa fa-qrcode fa-1x"></i> fa-qrcode</li>
<li><i class="fa fa-question fa-1x"></i> fa-question</li>
<li><i class="fa fa-question-circle fa-1x"></i> fa-question-circle</li>
<li><i class="fa fa-quote-left fa-1x"></i> fa-quote-left</li>
<li><i class="fa fa-quote-right fa-1x"></i> fa-quote-right</li>
<li><i class="fa fa-random fa-1x"></i> fa-random</li>
<li><i class="fa fa-recycle fa-1x"></i> fa-recycle</li>
<li><i class="fa fa-refresh fa-1x"></i> fa-refresh</li>
<li><i class="fa fa-remove fa-1x"></i> fa-remove <small>(alias)</small></li>
<li><i class="fa fa-reorder fa-1x"></i> fa-reorder <small>(alias)</small></li>
<li><i class="fa fa-reply fa-1x"></i> fa-reply</li>
<li><i class="fa fa-reply-all fa-1x"></i> fa-reply-all</li>
<li><i class="fa fa-retweet fa-1x"></i> fa-retweet</li>
<li><i class="fa fa-road fa-1x"></i> fa-road</li>
<li><i class="fa fa-rocket fa-1x"></i> fa-rocket</li>
<li><i class="fa fa-rss fa-1x"></i> fa-rss</li>
<li><i class="fa fa-rss-square fa-1x"></i> fa-rss-square</li>
<li><i class="fa fa-search fa-1x"></i> fa-search</li>
<li><i class="fa fa-search-minus fa-1x"></i> fa-search-minus</li>
<li><i class="fa fa-search-plus fa-1x"></i> fa-search-plus</li>
<li><i class="fa fa-send fa-1x"></i> fa-send <small>(alias)</small></li>
<li><i class="fa fa-send-o fa-1x"></i> fa-send-o <small>(alias)</small></li>
<li><i class="fa fa-share fa-1x"></i> fa-share</li>
<li><i class="fa fa-share-alt fa-1x"></i> fa-share-alt</li>
<li><i class="fa fa-share-alt-square fa-1x"></i> fa-share-alt-square</li>
<li><i class="fa fa-share-square fa-1x"></i> fa-share-square</li>
<li><i class="fa fa-share-square-o fa-1x"></i> fa-share-square-o</li>
<li><i class="fa fa-shield fa-1x"></i> fa-shield</li>
<li><i class="fa fa-shopping-cart fa-1x"></i> fa-shopping-cart</li>
<li><i class="fa fa-sign-in fa-1x"></i> fa-sign-in</li>
<li><i class="fa fa-sign-out fa-1x"></i> fa-sign-out</li>
<li><i class="fa fa-signal fa-1x"></i> fa-signal</li>
<li><i class="fa fa-sitemap fa-1x"></i> fa-sitemap</li>
<li><i class="fa fa-sliders fa-1x"></i> fa-sliders</li>
<li><i class="fa fa-smile-o fa-1x"></i> fa-smile-o</li>
<li><i class="fa fa-soccer-ball-o fa-1x"></i> fa-soccer-ball-o <small>(alias)</small></li>
<li><i class="fa fa-sort fa-1x"></i> fa-sort</li>
<li><i class="fa fa-sort-alpha-asc fa-1x"></i> fa-sort-alpha-asc</li>
<li><i class="fa fa-sort-alpha-desc fa-1x"></i> fa-sort-alpha-desc</li>
<li><i class="fa fa-sort-amount-asc fa-1x"></i> fa-sort-amount-asc</li>
<li><i class="fa fa-sort-amount-desc fa-1x"></i> fa-sort-amount-desc</li>
<li><i class="fa fa-sort-asc fa-1x"></i> fa-sort-asc</li>
<li><i class="fa fa-sort-desc fa-1x"></i> fa-sort-desc</li>
<li><i class="fa fa-sort-down fa-1x"></i> fa-sort-down <small>(alias)</small></li>
<li><i class="fa fa-sort-numeric-asc fa-1x"></i> fa-sort-numeric-asc</li>
<li><i class="fa fa-sort-numeric-desc fa-1x"></i> fa-sort-numeric-desc</li>
<li><i class="fa fa-sort-up fa-1x"></i> fa-sort-up <small>(alias)</small></li>
<li><i class="fa fa-space-shuttle fa-1x"></i> fa-space-shuttle</li>
<li><i class="fa fa-spinner fa-1x"></i> fa-spinner</li>
<li><i class="fa fa-spoon fa-1x"></i> fa-spoon</li>
<li><i class="fa fa-square fa-1x"></i> fa-square</li>
<li><i class="fa fa-square-o fa-1x"></i> fa-square-o</li>
<li><i class="fa fa-star fa-1x"></i> fa-star</li>
<li><i class="fa fa-star-half fa-1x"></i> fa-star-half</li>
<li><i class="fa fa-star-half-empty fa-1x"></i> fa-star-half-empty <small>(alias)</small></li>
<li><i class="fa fa-star-half-full fa-1x"></i> fa-star-half-full <small>(alias)</small></li>
<li><i class="fa fa-star-half-o fa-1x"></i> fa-star-half-o</li>
<li><i class="fa fa-star-o fa-1x"></i> fa-star-o</li>
<li><i class="fa fa-suitcase fa-1x"></i> fa-suitcase</li>
<li><i class="fa fa-sun-o fa-1x"></i> fa-sun-o</li>
<li><i class="fa fa-support fa-1x"></i> fa-support <small>(alias)</small></li>
<li><i class="fa fa-tablet fa-1x"></i> fa-tablet</li>
<li><i class="fa fa-tachometer fa-1x"></i> fa-tachometer</li>
<li><i class="fa fa-tag fa-1x"></i> fa-tag</li>
<li><i class="fa fa-tags fa-1x"></i> fa-tags</li>
<li><i class="fa fa-tasks fa-1x"></i> fa-tasks</li>
<li><i class="fa fa-taxi fa-1x"></i> fa-taxi</li>
<li><i class="fa fa-terminal fa-1x"></i> fa-terminal</li>
<li><i class="fa fa-thumb-tack fa-1x"></i> fa-thumb-tack</li>
<li><i class="fa fa-thumbs-down fa-1x"></i> fa-thumbs-down</li>
<li><i class="fa fa-thumbs-o-down fa-1x"></i> fa-thumbs-o-down</li>
<li><i class="fa fa-thumbs-o-up fa-1x"></i> fa-thumbs-o-up</li>
<li><i class="fa fa-thumbs-up fa-1x"></i> fa-thumbs-up</li>
<li><i class="fa fa-ticket fa-1x"></i> fa-ticket</li>
<li><i class="fa fa-times fa-1x"></i> fa-times</li>
<li><i class="fa fa-times-circle fa-1x"></i> fa-times-circle</li>
<li><i class="fa fa-times-circle-o fa-1x"></i> fa-times-circle-o</li>
<li><i class="fa fa-tint fa-1x"></i> fa-tint</li>
<li><i class="fa fa-toggle-down fa-1x"></i> fa-toggle-down <small>(alias)</small></li>
<li><i class="fa fa-toggle-left fa-1x"></i> fa-toggle-left <small>(alias)</small></li>
<li><i class="fa fa-toggle-off fa-1x"></i> fa-toggle-off</li>
<li><i class="fa fa-toggle-on fa-1x"></i> fa-toggle-on</li>
<li><i class="fa fa-toggle-right fa-1x"></i> fa-toggle-right <small>(alias)</small></li>
<li><i class="fa fa-toggle-up fa-1x"></i> fa-toggle-up <small>(alias)</small></li>
<li><i class="fa fa-trash fa-1x"></i> fa-trash</li>
<li><i class="fa fa-trash-o fa-1x"></i> fa-trash-o</li>
<li><i class="fa fa-tree fa-1x"></i> fa-tree</li>
<li><i class="fa fa-trophy fa-1x"></i> fa-trophy</li>
<li><i class="fa fa-truck fa-1x"></i> fa-truck</li>
<li><i class="fa fa-tty fa-1x"></i> fa-tty</li>
<li><i class="fa fa-umbrella fa-1x"></i> fa-umbrella</li>
<li><i class="fa fa-university fa-1x"></i> fa-university</li>
<li><i class="fa fa-unlock fa-1x"></i> fa-unlock</li>
<li><i class="fa fa-unlock-alt fa-1x"></i> fa-unlock-alt</li>
<li><i class="fa fa-unsorted fa-1x"></i> fa-unsorted <small>(alias)</small></li>
<li><i class="fa fa-upload fa-1x"></i> fa-upload</li>
<li><i class="fa fa-user fa-1x"></i> fa-user</li>
<li><i class="fa fa-users fa-1x"></i> fa-users</li>
<li><i class="fa fa-video-camera fa-1x"></i> fa-video-camera</li>
<li><i class="fa fa-volume-down fa-1x"></i> fa-volume-down</li>
<li><i class="fa fa-volume-off fa-1x"></i> fa-volume-off</li>
<li><i class="fa fa-volume-up fa-1x"></i> fa-volume-up</li>
<li><i class="fa fa-warning fa-1x"></i> fa-warning <small>(alias)</small></li>
<li><i class="fa fa-wheelchair fa-1x"></i> fa-wheelchair</li>
<li><i class="fa fa-wifi fa-1x"></i> fa-wifi</li>
<li><i class="fa fa-wrench fa-1x"></i> fa-wrench</li>
</ul>

<h4>File Type Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-file fa-1x"></i> fa-file</li>
<li><i class="fa fa-file-archive-o fa-1x"></i> fa-file-archive-o</li>
<li><i class="fa fa-file-audio-o fa-1x"></i> fa-file-audio-o</li>
<li><i class="fa fa-file-code-o fa-1x"></i> fa-file-code-o</li>
<li><i class="fa fa-file-excel-o fa-1x"></i> fa-file-excel-o</li>
<li><i class="fa fa-file-image-o fa-1x"></i> fa-file-image-o</li>
<li><i class="fa fa-file-movie-o fa-1x"></i> fa-file-movie-o <small>(alias)</small></li>
<li><i class="fa fa-file-o fa-1x"></i> fa-file-o</li>
<li><i class="fa fa-file-pdf-o fa-1x"></i> fa-file-pdf-o</li>
<li><i class="fa fa-file-photo-o fa-1x"></i> fa-file-photo-o <small>(alias)</small></li>
<li><i class="fa fa-file-picture-o fa-1x"></i> fa-file-picture-o <small>(alias)</small></li>
<li><i class="fa fa-file-powerpoint-o fa-1x"></i> fa-file-powerpoint-o</li>
<li><i class="fa fa-file-sound-o fa-1x"></i> fa-file-sound-o <small>(alias)</small></li>
<li><i class="fa fa-file-text fa-1x"></i> fa-file-text</li>
<li><i class="fa fa-file-text-o fa-1x"></i> fa-file-text-o</li>
<li><i class="fa fa-file-video-o fa-1x"></i> fa-file-video-o</li>
<li><i class="fa fa-file-word-o fa-1x"></i> fa-file-word-o</li>
<li><i class="fa fa-file-zip-o fa-1x"></i> fa-file-zip-o <small>(alias)</small></li>
</ul>

<h4>Spinner Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-circle-o-notch fa-1x"></i> fa-circle-o-notch</li>
<li><i class="fa fa-cog fa-1x"></i> fa-cog</li>
<li><i class="fa fa-gear fa-1x"></i> fa-gear <small>(alias)</small></li>
<li><i class="fa fa-refresh fa-1x"></i> fa-refresh</li>
<li><i class="fa fa-spinner fa-1x"></i> fa-spinner</li>
</ul>

<h4>Form Control Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-check-square fa-1x"></i> fa-check-square</li>
<li><i class="fa fa-check-square-o fa-1x"></i> fa-check-square-o</li>
<li><i class="fa fa-circle fa-1x"></i> fa-circle</li>
<li><i class="fa fa-circle-o fa-1x"></i> fa-circle-o</li>
<li><i class="fa fa-dot-circle-o fa-1x"></i> fa-dot-circle-o</li>
<li><i class="fa fa-minus-square fa-1x"></i> fa-minus-square</li>
<li><i class="fa fa-minus-square-o fa-1x"></i> fa-minus-square-o</li>
<li><i class="fa fa-plus-square fa-1x"></i> fa-plus-square</li>
<li><i class="fa fa-plus-square-o fa-1x"></i> fa-plus-square-o</li>
<li><i class="fa fa-square fa-1x"></i> fa-square</li>
<li><i class="fa fa-square-o fa-1x"></i> fa-square-o</li>
</ul>

<h4>Payment Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-cc-amex fa-1x"></i> fa-cc-amex</li>
<li><i class="fa fa-cc-discover fa-1x"></i> fa-cc-discover</li>
<li><i class="fa fa-cc-mastercard fa-1x"></i> fa-cc-mastercard</li>
<li><i class="fa fa-cc-paypal fa-1x"></i> fa-cc-paypal</li>
<li><i class="fa fa-cc-stripe fa-1x"></i> fa-cc-stripe</li>
<li><i class="fa fa-cc-visa fa-1x"></i> fa-cc-visa</li>
<li><i class="fa fa-credit-card fa-1x"></i> fa-credit-card</li>
<li><i class="fa fa-google-wallet fa-1x"></i> fa-google-wallet</li>
<li><i class="fa fa-paypal fa-1x"></i> fa-paypal</li>
</ul>

<h4>Chart Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-area-chart fa-1x"></i> fa-area-chart</li>
<li><i class="fa fa-bar-chart fa-1x"></i> fa-bar-chart</li>
<li><i class="fa fa-bar-chart-o fa-1x"></i> fa-bar-chart-o <small>(alias)</small></li>
<li><i class="fa fa-line-chart fa-1x"></i> fa-line-chart</li>
<li><i class="fa fa-pie-chart fa-1x"></i> fa-pie-chart</li>
</ul>

<h4>Currency Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-bitcoin fa-1x"></i> fa-bitcoin <small>(alias)</small></li>
<li><i class="fa fa-btc fa-1x"></i> fa-btc</li>
<li><i class="fa fa-cny fa-1x"></i> fa-cny <small>(alias)</small></li>
<li><i class="fa fa-dollar fa-1x"></i> fa-dollar <small>(alias)</small></li>
<li><i class="fa fa-eur fa-1x"></i> fa-eur</li>
<li><i class="fa fa-euro fa-1x"></i> fa-euro <small>(alias)</small></li>
<li><i class="fa fa-gbp fa-1x"></i> fa-gbp</li>
<li><i class="fa fa-ils fa-1x"></i> fa-ils</li>
<li><i class="fa fa-inr fa-1x"></i> fa-inr</li>
<li><i class="fa fa-jpy fa-1x"></i> fa-jpy</li>
<li><i class="fa fa-krw fa-1x"></i> fa-krw</li>
<li><i class="fa fa-money fa-1x"></i> fa-money</li>
<li><i class="fa fa-rmb fa-1x"></i> fa-rmb <small>(alias)</small></li>
<li><i class="fa fa-rouble fa-1x"></i> fa-rouble <small>(alias)</small></li>
<li><i class="fa fa-rub fa-1x"></i> fa-rub</li>
<li><i class="fa fa-ruble fa-1x"></i> fa-ruble <small>(alias)</small></li>
<li><i class="fa fa-rupee fa-1x"></i> fa-rupee <small>(alias)</small></li>
<li><i class="fa fa-shekel fa-1x"></i> fa-shekel <small>(alias)</small></li>
<li><i class="fa fa-sheqel fa-1x"></i> fa-sheqel <small>(alias)</small></li>
<li><i class="fa fa-try fa-1x"></i> fa-try</li>
<li><i class="fa fa-turkish-lira fa-1x"></i> fa-turkish-lira <small>(alias)</small></li>
<li><i class="fa fa-usd fa-1x"></i> fa-usd</li>
<li><i class="fa fa-won fa-1x"></i> fa-won <small>(alias)</small></li>
<li><i class="fa fa-yen fa-1x"></i> fa-yen <small>(alias)</small></li>
</ul>

<h4>Text Editor Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-align-center fa-1x"></i> fa-align-center</li>
<li><i class="fa fa-align-justify fa-1x"></i> fa-align-justify</li>
<li><i class="fa fa-align-left fa-1x"></i> fa-align-left</li>
<li><i class="fa fa-align-right fa-1x"></i> fa-align-right</li>
<li><i class="fa fa-bold fa-1x"></i> fa-bold</li>
<li><i class="fa fa-chain fa-1x"></i> fa-chain <small>(alias)</small></li>
<li><i class="fa fa-chain-broken fa-1x"></i> fa-chain-broken</li>
<li><i class="fa fa-clipboard fa-1x"></i> fa-clipboard</li>
<li><i class="fa fa-columns fa-1x"></i> fa-columns</li>
<li><i class="fa fa-copy fa-1x"></i> fa-copy <small>(alias)</small></li>
<li><i class="fa fa-cut fa-1x"></i> fa-cut <small>(alias)</small></li>
<li><i class="fa fa-dedent fa-1x"></i> fa-dedent <small>(alias)</small></li>
<li><i class="fa fa-eraser fa-1x"></i> fa-eraser</li>
<li><i class="fa fa-file fa-1x"></i> fa-file</li>
<li><i class="fa fa-file-o fa-1x"></i> fa-file-o</li>
<li><i class="fa fa-file-text fa-1x"></i> fa-file-text</li>
<li><i class="fa fa-file-text-o fa-1x"></i> fa-file-text-o</li>
<li><i class="fa fa-files-o fa-1x"></i> fa-files-o</li>
<li><i class="fa fa-floppy-o fa-1x"></i> fa-floppy-o</li>
<li><i class="fa fa-font fa-1x"></i> fa-font</li>
<li><i class="fa fa-header fa-1x"></i> fa-header</li>
<li><i class="fa fa-indent fa-1x"></i> fa-indent</li>
<li><i class="fa fa-italic fa-1x"></i> fa-italic</li>
<li><i class="fa fa-link fa-1x"></i> fa-link</li>
<li><i class="fa fa-list fa-1x"></i> fa-list</li>
<li><i class="fa fa-list-alt fa-1x"></i> fa-list-alt</li>
<li><i class="fa fa-list-ol fa-1x"></i> fa-list-ol</li>
<li><i class="fa fa-list-ul fa-1x"></i> fa-list-ul</li>
<li><i class="fa fa-outdent fa-1x"></i> fa-outdent</li>
<li><i class="fa fa-paperclip fa-1x"></i> fa-paperclip</li>
<li><i class="fa fa-paragraph fa-1x"></i> fa-paragraph</li>
<li><i class="fa fa-paste fa-1x"></i> fa-paste <small>(alias)</small></li>
<li><i class="fa fa-repeat fa-1x"></i> fa-repeat</li>
<li><i class="fa fa-rotate-left fa-1x"></i> fa-rotate-left <small>(alias)</small></li>
<li><i class="fa fa-rotate-right fa-1x"></i> fa-rotate-right <small>(alias)</small></li>
<li><i class="fa fa-save fa-1x"></i> fa-save <small>(alias)</small></li>
<li><i class="fa fa-scissors fa-1x"></i> fa-scissors</li>
<li><i class="fa fa-strikethrough fa-1x"></i> fa-strikethrough</li>
<li><i class="fa fa-subscript fa-1x"></i> fa-subscript</li>
<li><i class="fa fa-superscript fa-1x"></i> fa-superscript</li>
<li><i class="fa fa-table fa-1x"></i> fa-table</li>
<li><i class="fa fa-text-height fa-1x"></i> fa-text-height</li>
<li><i class="fa fa-text-width fa-1x"></i> fa-text-width</li>
<li><i class="fa fa-th fa-1x"></i> fa-th</li>
<li><i class="fa fa-th-large fa-1x"></i> fa-th-large</li>
<li><i class="fa fa-th-list fa-1x"></i> fa-th-list</li>
<li><i class="fa fa-underline fa-1x"></i> fa-underline</li>
<li><i class="fa fa-undo fa-1x"></i> fa-undo</li>
<li><i class="fa fa-unlink fa-1x"></i> fa-unlink <small>(alias)</small></li>
</ul>

<h4>Directional Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-angle-double-down fa-1x"></i> fa-angle-double-down</li>
<li><i class="fa fa-angle-double-left fa-1x"></i> fa-angle-double-left</li>
<li><i class="fa fa-angle-double-right fa-1x"></i> fa-angle-double-right</li>
<li><i class="fa fa-angle-double-up fa-1x"></i> fa-angle-double-up</li>
<li><i class="fa fa-angle-down fa-1x"></i> fa-angle-down</li>
<li><i class="fa fa-angle-left fa-1x"></i> fa-angle-left</li>
<li><i class="fa fa-angle-right fa-1x"></i> fa-angle-right</li>
<li><i class="fa fa-angle-up fa-1x"></i> fa-angle-up</li>
<li><i class="fa fa-arrow-circle-down fa-1x"></i> fa-arrow-circle-down</li>
<li><i class="fa fa-arrow-circle-left fa-1x"></i> fa-arrow-circle-left</li>
<li><i class="fa fa-arrow-circle-o-down fa-1x"></i> fa-arrow-circle-o-down</li>
<li><i class="fa fa-arrow-circle-o-left fa-1x"></i> fa-arrow-circle-o-left</li>
<li><i class="fa fa-arrow-circle-o-right fa-1x"></i> fa-arrow-circle-o-right</li>
<li><i class="fa fa-arrow-circle-o-up fa-1x"></i> fa-arrow-circle-o-up</li>
<li><i class="fa fa-arrow-circle-right fa-1x"></i> fa-arrow-circle-right</li>
<li><i class="fa fa-arrow-circle-up fa-1x"></i> fa-arrow-circle-up</li>
<li><i class="fa fa-arrow-down fa-1x"></i> fa-arrow-down</li>
<li><i class="fa fa-arrow-left fa-1x"></i> fa-arrow-left</li>
<li><i class="fa fa-arrow-right fa-1x"></i> fa-arrow-right</li>
<li><i class="fa fa-arrow-up fa-1x"></i> fa-arrow-up</li>
<li><i class="fa fa-arrows fa-1x"></i> fa-arrows</li>
<li><i class="fa fa-arrows-alt fa-1x"></i> fa-arrows-alt</li>
<li><i class="fa fa-arrows-h fa-1x"></i> fa-arrows-h</li>
<li><i class="fa fa-arrows-v fa-1x"></i> fa-arrows-v</li>
<li><i class="fa fa-caret-down fa-1x"></i> fa-caret-down</li>
<li><i class="fa fa-caret-left fa-1x"></i> fa-caret-left</li>
<li><i class="fa fa-caret-right fa-1x"></i> fa-caret-right</li>
<li><i class="fa fa-caret-square-o-down fa-1x"></i> fa-caret-square-o-down</li>
<li><i class="fa fa-caret-square-o-left fa-1x"></i> fa-caret-square-o-left</li>
<li><i class="fa fa-caret-square-o-right fa-1x"></i> fa-caret-square-o-right</li>
<li><i class="fa fa-caret-square-o-up fa-1x"></i> fa-caret-square-o-up</li>
<li><i class="fa fa-caret-up fa-1x"></i> fa-caret-up</li>
<li><i class="fa fa-chevron-circle-down fa-1x"></i> fa-chevron-circle-down</li>
<li><i class="fa fa-chevron-circle-left fa-1x"></i> fa-chevron-circle-left</li>
<li><i class="fa fa-chevron-circle-right fa-1x"></i> fa-chevron-circle-right</li>
<li><i class="fa fa-chevron-circle-up fa-1x"></i> fa-___</li>
<li><i class="fa fa-chevron-down fa-1x"></i> fa-chevron-down</li>
<li><i class="fa fa-chevron-left fa-1x"></i> fa-chevron-left</li>
<li><i class="fa fa-chevron-right fa-1x"></i> fa-chevron-right</li>
<li><i class="fa fa-chevron-up fa-1x"></i> fa-chevron-up</li>
<li><i class="fa fa-hand-o-down fa-1x"></i> fa-hand-o-down</li>
<li><i class="fa fa-hand-o-left fa-1x"></i> fa-hand-o-left</li>
<li><i class="fa fa-hand-o-right fa-1x"></i> fa-hand-o-right</li>
<li><i class="fa fa-hand-o-up fa-1x"></i> fa-hand-o-up</li>
<li><i class="fa fa-long-arrow-down fa-1x"></i> fa-long-arrow-down</li>
<li><i class="fa fa-long-arrow-left fa-1x"></i> fa-long-arrow-left</li>
<li><i class="fa fa-long-arrow-right fa-1x"></i> fa-long-arrow-right</li>
<li><i class="fa fa-long-arrow-up fa-1x"></i> fa-long-arrow-up</li>
<li><i class="fa fa-toggle-down fa-1x"></i> fa-toggle-down <small>(alias)</small></li>
<li><i class="fa fa-toggle-left fa-1x"></i> fa-toggle-left <small>(alias)</small></li>
<li><i class="fa fa-toggle-right fa-1x"></i> fa-toggle-right <small>(alias)</small></li>
<li><i class="fa fa-toggle-up fa-1x"></i> fa-toggle-up <small>(alias)</small></li>
</ul>

<h4>Video Player Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-arrows-alt fa-1x"></i> fa-arrows-alt</li>
<li><i class="fa fa-backward fa-1x"></i> fa-backward</li>
<li><i class="fa fa-compress fa-1x"></i> fa-compress</li>
<li><i class="fa fa-eject fa-1x"></i> fa-eject</li>
<li><i class="fa fa-expand fa-1x"></i> fa-expand</li>
<li><i class="fa fa-fast-backward fa-1x"></i> fa-fast-backward</li>
<li><i class="fa fa-fast-forward fa-1x"></i> fa-fast-forward</li>
<li><i class="fa fa-forward fa-1x"></i> fa-forward</li>
<li><i class="fa fa-pause fa-1x"></i> fa-pause</li>
<li><i class="fa fa-play fa-1x"></i> fa-play</li>
<li><i class="fa fa-play-circle fa-1x"></i> fa-play-circle</li>
<li><i class="fa fa-play-circle-o fa-1x"></i> fa-play-circle-o</li>
<li><i class="fa fa-step-backward fa-1x"></i> fa-step-backward</li>
<li><i class="fa fa-step-forward fa-1x"></i> fa-step-forward</li>
<li><i class="fa fa-stop fa-1x"></i> fa-stop</li>
<li><i class="fa fa-youtube-play fa-1x"></i> fa-youtube-play</li>
</ul>

<h4>Brand Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-adn fa-1x"></i> fa-adn</li>
<li><i class="fa fa-android fa-1x"></i> fa-android</li>
<li><i class="fa fa-angellist fa-1x"></i> fa-angellist</li>
<li><i class="fa fa-apple fa-1x"></i> fa-apple</li>
<li><i class="fa fa-behance fa-1x"></i> fa-behance</li>
<li><i class="fa fa-behance-square fa-1x"></i> fa-behance-square</li>
<li><i class="fa fa-bitbucket fa-1x"></i> fa-bitbucket</li>
<li><i class="fa fa-bitbucket-square fa-1x"></i> fa-bitbucket-square</li>
<li><i class="fa fa-bitcoin fa-1x"></i> fa-bitcoin <small>(alias)</small></li>
<li><i class="fa fa-btc fa-1x"></i> fa-btc</li>
<li><i class="fa fa-cc-amex fa-1x"></i> fa-cc-amex</li>
<li><i class="fa fa-cc-discover fa-1x"></i> fa-cc-discover</li>
<li><i class="fa fa-cc-mastercard fa-1x"></i> fa-cc-mastercard</li>
<li><i class="fa fa-cc-paypal fa-1x"></i> fa-cc-paypal</li>
<li><i class="fa fa-cc-stripe fa-1x"></i> fa-cc-stripe</li>
<li><i class="fa fa-cc-visa fa-1x"></i> fa-cc-visa</li>
<li><i class="fa fa-codepen fa-1x"></i> fa-codepen</li>
<li><i class="fa fa-css3 fa-1x"></i> fa-css3</li>
<li><i class="fa fa-delicious fa-1x"></i> fa-delicious</li>
<li><i class="fa fa-deviantart fa-1x"></i> fa-deviantart</li>
<li><i class="fa fa-digg fa-1x"></i> fa-digg</li>
<li><i class="fa fa-dribbble fa-1x"></i> fa-dribbble</li>
<li><i class="fa fa-dropbox fa-1x"></i> fa-dropbox</li>
<li><i class="fa fa-drupal fa-1x"></i> fa-drupal</li>
<li><i class="fa fa-empire fa-1x"></i> fa-empire</li>
<li><i class="fa fa-facebook fa-1x"></i> fa-facebook</li>
<li><i class="fa fa-facebook-square fa-1x"></i> fa-facebook-square</li>
<li><i class="fa fa-flickr fa-1x"></i> fa-flickr</li>
<li><i class="fa fa-foursquare fa-1x"></i> fa-foursquare</li>
<li><i class="fa fa-ge fa-1x"></i> fa-ge <small>(alias)</small></li>
<li><i class="fa fa-git fa-1x"></i> fa-git</li>
<li><i class="fa fa-git-square fa-1x"></i> fa-git-square</li>
<li><i class="fa fa-github fa-1x"></i> fa-github</li>
<li><i class="fa fa-github-alt fa-1x"></i> fa-github-alt</li>
<li><i class="fa fa-github-square fa-1x"></i> fa-github-square</li>
<li><i class="fa fa-gittip fa-1x"></i> fa-gittip</li>
<li><i class="fa fa-google fa-1x"></i> fa-google</li>
<li><i class="fa fa-google-plus fa-1x"></i> fa-google-plus</li>
<li><i class="fa fa-google-plus-square fa-1x"></i> fa-google-plus-square</li>
<li><i class="fa fa-google-wallet fa-1x"></i> fa-google-wallet</li>
<li><i class="fa fa-hacker-news fa-1x"></i> fa-hacker-news</li>
<li><i class="fa fa-html5 fa-1x"></i> fa-html5</li>
<li><i class="fa fa-instagram fa-1x"></i> fa-instagram</li>
<li><i class="fa fa-ioxhost fa-1x"></i> fa-ioxhost</li>
<li><i class="fa fa-joomla fa-1x"></i> fa-joomla</li>
<li><i class="fa fa-jsfiddle fa-1x"></i> fa-jsfiddle</li>
<li><i class="fa fa-lastfm fa-1x"></i> fa-lastfm</li>
<li><i class="fa fa-lastfm-square fa-1x"></i> fa-lastfm-square</li>
<li><i class="fa fa-linkedin fa-1x"></i> fa-linkedin</li>
<li><i class="fa fa-linkedin-square fa-1x"></i> fa-linkedin-square</li>
<li><i class="fa fa-linux fa-1x"></i> fa-linux</li>
<li><i class="fa fa-maxcdn fa-1x"></i> fa-maxcdn</li>
<li><i class="fa fa-meanpath fa-1x"></i> fa-meanpath</li>
<li><i class="fa fa-openid fa-1x"></i> fa-openid</li>
<li><i class="fa fa-pagelines fa-1x"></i> fa-pagelines</li>
<li><i class="fa fa-paypal fa-1x"></i> fa-paypal</li>
<li><i class="fa fa-pied-piper fa-1x"></i> fa-pied-piper</li>
<li><i class="fa fa-pied-piper-alt fa-1x"></i> fa-pied-piper-alt</li>
<li><i class="fa fa-pinterest fa-1x"></i> fa-pinterest</li>
<li><i class="fa fa-pinterest-square fa-1x"></i> fa-pinterest-square</li>
<li><i class="fa fa-qq fa-1x"></i> fa-qq</li>
<li><i class="fa fa-ra fa-1x"></i> fa-ra <small>(alias)</small></li>
<li><i class="fa fa-rebel fa-1x"></i> fa-rebel</li>
<li><i class="fa fa-reddit fa-1x"></i> fa-reddit</li>
<li><i class="fa fa-reddit-square fa-1x"></i> fa-reddit-square</li>
<li><i class="fa fa-renren fa-1x"></i> fa-renren</li>
<li><i class="fa fa-share-alt fa-1x"></i> fa-share-alt</li>
<li><i class="fa fa-share-alt-square fa-1x"></i> fa-share-alt-square</li>
<li><i class="fa fa-skype fa-1x"></i> fa-skype</li>
<li><i class="fa fa-slack fa-1x"></i> fa-slack</li>
<li><i class="fa fa-slideshare fa-1x"></i> fa-slideshare</li>
<li><i class="fa fa-soundcloud fa-1x"></i> fa-soundcloud</li>
<li><i class="fa fa-spotify fa-1x"></i> fa-spotify</li>
<li><i class="fa fa-stack-exchange fa-1x"></i> fa-stack-exchange</li>
<li><i class="fa fa-stack-overflow fa-1x"></i> fa-stack-overflow</li>
<li><i class="fa fa-steam fa-1x"></i> fa-steam</li>
<li><i class="fa fa-steam-square fa-1x"></i> fa-steam-square</li>
<li><i class="fa fa-stumbleupon fa-1x"></i> fa-stumbleupon</li>
<li><i class="fa fa-stumbleupon-circle fa-1x"></i> fa-stumbleupon-circle</li>
<li><i class="fa fa-tencent-weibo fa-1x"></i> fa-tencent-weibo</li>
<li><i class="fa fa-trello fa-1x"></i> fa-trello</li>
<li><i class="fa fa-tumblr fa-1x"></i> fa-tumblr</li>
<li><i class="fa fa-tumblr-square fa-1x"></i> fa-tumblr-square</li>
<li><i class="fa fa-twitch fa-1x"></i> fa-twitch</li>
<li><i class="fa fa-twitter fa-1x"></i> fa-twitter</li>
<li><i class="fa fa-twitter-square fa-1x"></i> fa-twitter-square</li>
<li><i class="fa fa-vimeo-square fa-1x"></i> fa-vimeo-square</li>
<li><i class="fa fa-vine fa-1x"></i> fa-vine</li>
<li><i class="fa fa-vk fa-1x"></i> fa-vk</li>
<li><i class="fa fa-wechat fa-1x"></i> fa-wechat <small>(alias)</small></li>
<li><i class="fa fa-weibo fa-1x"></i> fa-weibo</li>
<li><i class="fa fa-weixin fa-1x"></i> fa-weixin</li>
<li><i class="fa fa-windows fa-1x"></i> fa-windows</li>
<li><i class="fa fa-wordpress fa-1x"></i> fa-wordpress</li>
<li><i class="fa fa-xing fa-1x"></i> fa-xing</li>
<li><i class="fa fa-xing-square fa-1x"></i> fa-xing-square</li>
<li><i class="fa fa-yahoo fa-1x"></i> fa-yahoo</li>
<li><i class="fa fa-yelp fa-1x"></i> fa-yelp</li>
<li><i class="fa fa-youtube fa-1x"></i> fa-youtube</li>
<li><i class="fa fa-youtube-play fa-1x"></i> fa-youtube-play</li>
<li><i class="fa fa-youtube-square fa-1x"></i> fa-youtube-square</li>
</ul>

<h4>Medical Icons</h4>

<ul class="font-awesome-list">
<li><i class="fa fa-ambulance fa-1x"></i> fa-ambulance</li>
<li><i class="fa fa-h-square fa-1x"></i> fa-h-square</li>
<li><i class="fa fa-hospital-o fa-1x"></i> fa-hospital-o</li>
<li><i class="fa fa-medkit fa-1x"></i> fa-medkit</li>
<li><i class="fa fa-plus-square fa-1x"></i> fa-plus-square</li>
<li><i class="fa fa-stethoscope fa-1x"></i> fa-stethoscope</li>
<li><i class="fa fa-user-md fa-1x"></i> fa-user-md</li>
<li><i class="fa fa-wheelchair fa-1x"></i> fa-wheelchair</li>
</ul>

</div>
</div>